# Database for testing
development:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DEV_DB_DATABASE'] %>
  pool: 5
  username: <%= ENV['DEV_DB_USERNAME'] || 'root' %>
  password: <%= ENV['DEV_DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DEV_DB_HOST'] || 'localhost' %>
  port: 3306

# Actual database (password stored in .env)
production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB_DATABASE'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 3306


